-- DROPS
DROP TABLE if exists sfa.communication
DROP TABLE if exists sfa.correspondence_type_batch_param
DROP TABLE if exists sfa.correspondence_batch_param
DROP TABLE if exists sfa.correspondence
DROP TABLE if exists sfa.correspondence_type
DROP TABLE if exists sfa.dependent
DROP TABLE if exists sfa.education
DROP TABLE if exists sfa.expense_category
DROP TABLE if exists sfa.institution_request_type
DROP TABLE if exists sfa.request_requirement
DROP TABLE if exists sfa.request_type
DROP TABLE if exists sfa.residence
DROP TABLE if exists sfa.student_consent
DROP TABLE if exists sfa.yg_cost
DROP TABLE if exists sfa.yea_update
DROP TABLE if exists sfa.yea
DROP TABLE if exists sfa.verification_log
DROP TABLE if exists sfa.transportation
DROP TABLE if exists sfa.system_parameter
DROP TABLE if exists sfa.system_dep_params
DROP TABLE if exists sfa.study_tax_rate
DROP TABLE if exists sfa.study_area
DROP TABLE if exists sfa.study_field
DROP TABLE if exists sfa.student_living_allowance
DROP TABLE if exists sfa.student_contribution
DROP TABLE if exists sfa.student_category
DROP TABLE if exists sfa.status_reason
DROP TABLE if exists sfa.status
DROP TABLE if exists sfa.standard_of_living
DROP TABLE if exists sfa.sta_lookup
DROP TABLE if exists sfa.spouse_tax_rate
DROP TABLE if exists sfa.sfa_document_link
DROP TABLE if exists sfa.requirement_type
DROP TABLE if exists sfa.report_expense_category
DROP TABLE if exists sfa.prestudy_tax_rate
DROP TABLE if exists sfa.prestudy_employment_status
DROP TABLE if exists sfa.portal_status
DROP TABLE if exists sfa.period
DROP TABLE if exists sfa.part_time_reason
DROP TABLE if exists sfa.parent_contribution_formula
DROP TABLE if exists sfa.ownership
DROP TABLE if exists sfa.marital_status
DROP TABLE if exists sfa.investment_type
DROP TABLE if exists sfa.instruction_type
DROP TABLE if exists sfa.info_category
DROP TABLE if exists sfa.funding_group
DROP TABLE if exists sfa.first_nation
DROP TABLE if exists sfa.entitlement_error_codes
DROP TABLE if exists sfa.disbursement_type
DROP TABLE if exists sfa.disability_type
DROP TABLE if exists sfa.disability_service
DROP TABLE if exists sfa.csl_restricted
DROP TABLE if exists sfa.csl_reason
DROP TABLE if exists sfa.csl_nslsc_address
DROP TABLE if exists sfa.csl_lookup
DROP TABLE if exists sfa.csl_code
DROP TABLE if exists sfa.csg_threshold
DROP TABLE if exists sfa.csg_lookup
DROP TABLE if exists sfa.communication_type
DROP TABLE if exists sfa.child_care_ceiling
DROP TABLE if exists sfa.change_reason
DROP TABLE if exists sfa.category
DROP TABLE if exists sfa.batch_parameter
DROP TABLE if exists sfa.batch_group
DROP TABLE if exists sfa.assessment_type
DROP TABLE if exists sfa.application_type
DROP TABLE if exists sfa.agency
DROP TABLE if exists sfa.age_distribution
DROP TABLE if exists sfa.aboriginal_status
DROP TABLE if exists sfa.student_persons
DROP TABLE if exists sfa.student
DROP TABLE if exists sfa.high_school
DROP TABLE if exists sfa.person
DROP TABLE if exists sfa.person_address
DROP TABLE if exists sfa.address_type
DROP TABLE IF EXISTS sfa.sex
DROP TABLE if exists sfa.relationship
DROP TABLE if exists sfa.program
DROP TABLE if exists sfa.field_program
DROP TABLE if exists sfa.language
DROP TABLE if exists sfa.education_level
DROP TABLE if exists sfa.institution_campus_dates
DROP TABLE if exists sfa.institution_campus_notes
DROP TABLE if exists sfa.institution_campus
DROP TABLE if exists sfa.institution
DROP TABLE if exists sfa.institution_level
DROP TABLE if exists sfa.city
DROP TABLE if exists sfa.province
DROP TABLE if exists sfa.country
DROP TABLE if exists sfa.indigenous_learner
DROP TABLE if exists sfa.academic_year
--DROP TABLE sfa.user