'https://plantuml.com/activity-diagram-beta

@startuml
start

:Receive funding request;

if (Has 0 assessments?) then (yes)
  :Assessments section is blank;
elseif (Has 1 assessment?) then (yes)
  :Assessments section has 1 section;
  note right
    e.g.
    Rate per Week: $144.00
    Approv. Weeks: 32
    Travel/Airfare: $0.00
  end note
else (has many assessments)
  :Assessments section has many sub-sections;
  note right
    e.g.
    Rate per Week: $144.00
    Approv. Weeks: 32
    Travel/Airfare: $0.00

    Rate per Week: $144.00
    Approv. Weeks: 32
    Travel/Airfare: $0.00
  end note
endif

if (Has 0 disbursements?) then (yes)
  :Generate letter AAA;
  note right
    Here, you can
    embed the image
    of letter AAA
  end note
else (no)
  if (Has 1 disbursement?) then (yes)
    :Generate letter BBB;
    note right
      Here, you can
      embed the image
      of letter BBB
    end note
  else (has many disbursements)
    :Generate letter CCC;
    note right
      Here, you can
      embed the image
      of letter CCC
    end note
  endif
endif

stop
@enduml
