@startuml
entity AddressType {
  id: number
  description: string
  is_active: boolean
}

entity Application {
  id: number
  student_id: number
  academic_year_id: number
  institution_campus_id?: number
  study_area_id?: number
  program_id?: number
  aboriginal_status_id?: number
  marital_status_id?: number
  category_id?: number
  first_nation_id?: number
  spouse_id?: number
  parent1_id?: number
  parent2_id?: number
  primary_address_id?: number
  parent1_relationship_id?: number
  parent2_relationship_id?: number
  parent1_income?: number
  parent1_net_income?: number
  parent1_tax_paid?: number
  parent2_income?: number
  parent2_net_income?: number
  parent2_tax_paid?: number
  school_email?: string
  school_telephone?: string
  spouse_hs_end_year?: number
  spouse_hs_end_month?: number
  spouse_prestudy_emp_status_id?: number
  spouse_pstudy_school_from?: Date
  spouse_pstudy_school_to?: Date
  spouse_pstudy_income_comment?: string
  spouse_study_emp_status_id?: number
  spouse_study_school_from?: Date
  spouse_study_school_to?: Date
  is_spouse_study_csl: boolean
  is_spouse_study_bus: boolean
  spouse_study_distance?: number
  spouse_study_income_comment?: string
  classes_start_date?: Date
  classes_end_date?: Date
  is_correspondence: boolean
  is_coop_paid: boolean
  citizenship_status?: number
  is_disabled: boolean
  is_minority: boolean
  student_number?: string
  program_year_total?: number
  program_year?: number
  is_two_residence: boolean
  is_moving: boolean
  csl_classification?: number
  csl_previous_province_id?: number
  program_division_explanation?: string
  prestudy_accom_code?: number
  prestudy_own_home: boolean
  prestudy_board_amount?: number
  prestudy_city_id?: number
  prestudy_province_id?: number
  prestudy_bus: boolean
  prestudy_distance?: number
  prestudy_employ_status_id?: number
  prestudy_employed_from_date?: Date
  prestudy_employed_to_date?: Date
  prestudy_employer_name?: string
  prestudy_employer_city_id?: number
  prestudy_employer_province_id?: number
  study_accom_code?: number
  study_own_home: boolean
  study_board_amount?: number
  study_city_id?: number
  study_province_id?: number
  study_bus: boolean
  study_distance?: number
  stat_info_comment?: string
  books_supplies_cost?: number
  outstanding_cslpt_amount?: number
  previous_csg_pt_amount?: number
  percent_of_full_time?: number
  is_part_of_ft: boolean
  study_weeks_count?: number
  class_hours_per_week?: number
  parent_residence_comment?: string
  study_living_w_spouse: boolean
  prestudy_living_w_spouse: boolean
  tuition_estimate_amount?: number
  program_division?: number
  is_previous_cslft: boolean
  is_previous_cslpt: boolean
  coop_start_year?: number
  coop_start_month?: number
  coop_end_year?: number
  coop_end_month?: number
  exclude_from_count: boolean
  is_perm_disabled: boolean
  disabled_equipment?: string
  previous_csg_disability_amount?: number
  previous_csg_fem_doc_amount?: number
  credit_chk_reqd_date?: Date
  credit_chk_fax_sent_date?: Date
  credit_chk_passed_date?: Date
  credit_chk_passed: boolean
  credit_chk_appeal_date?: Date
  credit_chk_app_comp_date?: Date
  credit_chk_app_comp: boolean
  credit_chk_comp_date?: Date
  csl_clearance_date?: Date
  prestudy_csl_classification?: number
  yea_tot_receipt_amount?: number
  academic_percent?: number
  csl_restriction_comment?: string
  in_progress_page?: number
  online_start_date?: Date
  online_submit_date?: Date
  rem_transition_grant_years?: number
  student_ln150_income?: number
  spouse_ln150_income?: number
  taxes1_filed_year?: number
  taxes2_filed_year?: number
  taxes1_filed_province_id?: number
  taxes2_filed_province_id?: number
  taxes1_not_filed: boolean
  taxes2_not_filed: boolean
  taxes1_verified: boolean
  taxes2_verified: boolean
  applied_other_funding: boolean
  csl_restriction_warn_id?: number
  csl_restriction_reason_id?: number
  courses_per_week?: number
  prestudy_start_date?: Date
  prestudy_end_date?: Date
  valid_driver_license?: boolean
  valid_driver_license_comment?: string
  valid_yhcip?: boolean
  valid_yhcip_comment?: string
  attendance_id?: number
  has_consent_to_share_data: boolean
  permanent_disability: boolean
  pers_or_prolong_disability: boolean
  disability_start_date?: Date
  requires_credit_check: boolean
  last_checked_on?: Date
  seen: boolean
  updated_at?: Date
  last_jurisdiction_id?: number
  other_jurisdiction?: string
  spouse_last_jurisdiction_id?: number
  spouse_other_jurisdiction?: string
  is_persist_disabled: boolean
  persist_disabled_start_date?: Date
  is_cheques_to_institution: boolean
}

entity Assessment {
  id: number
  allowed_books?: number
  allowed_months?: number
  allowed_percent?: number
  allowed_tuition?: number
  assessed_amount?: number
  assessed_date?: Date
  change_reason_comment?: string
  dependent_count?: number
  effective_rate_date?: Date
  home_city_id?: number
  living_costs?: number
  travel_allowance?: number
  weekly_amount?: number
  assessment_type_id?: number
  destination_city_id?: number
  funding_request_id?: number
  disbursements_required?: number
  weeks_allowed?: number
  second_residence_rate?: number
  classes_end_date?: Date
  prestudy_accom_code?: number
  prestudy_province_id?: number
  classes_start_date?: Date
  airfare_amount?: number
  air_travel_disbursement_period?: number
  shelter_month?: number
  p_trans_month?: number
  r_trans16wk?: number
  day_care_allowable?: number
  depend_food_allowable?: number
  depend_tran_allowable?: number
  pstudy_shelter_month?: number
  pstudy_p_trans_month?: number
  pstudy_day_care_allow?: number
  pstudy_depend_food_allow?: number
  pstudy_depend_tran_allow?: number
  pstudy_start_date?: Date
  pstudy_end_date?: Date
  csl_assessed_need?: number
  study_province_id?: number
  csl_over_reason_id?: number
  csl_non_reason_id?: number
  over_award?: number
  student_tax_rate?: number
  spouse_tax_rate?: number
  spouse_pstudy_tax_rate?: number
  stud_pstudy_tax_rate?: number
  parent1_income?: number
  parent2_income?: number
  parent1_tax_paid?: number
  parent2_tax_paid?: number
  books_supplies_cost?: number
  tuition_estimate?: number
  uncapped_costs_total?: number
  uncapped_pstudy_total?: number
  day_care_actual?: number
  stud_pstudy_gross?: number
  spouse_pstudy_gross?: number
  pstudy_day_care_actual?: number
  student_gross_income?: number
  spouse_gross_income?: number
  prestudy_csl_classification?: number
  marital_status_id?: number
  spouse_province_id?: number
  study_accom_code?: number
  csl_classification?: number
  family_size?: number
  parent_ps_depend_count?: number
  discretionary_cost?: number
  discretionary_cost_actual?: number
  study_distance?: number
  prestudy_distance?: number
  prestudy_bus_flag?: number
  study_bus_flag?: number
  study_living_w_spouse_flag?: number
  prestudy_living_w_spouse_flag?: number
  csl_full_amt_flag?: number
  study_area_id?: number
  program_id?: number
  period?: string
  csl_request_amount?: number
  return_uncashable_cert?: number
  years_funded_equivalent?: number
  study_weeks?: number
  study_months?: number
  pstudy_expected_contrib?: number
  spouse_expected_income?: number
  asset_tax_rate?: number
  x_trans_total?: number
  relocation_total?: number
  pstudy_x_trans_total?: number
  married_pstudy?: number
  married_study?: number
  married_assets?: number
  entitlement_days?: number
  parent_contribution_override?: number
  total_grant_awarded?: number
  over_award_disbursement_period?: number
  over_award_applied_flg?: string
  pre_leg_amount?: number
  assessment_adj_amount?: number
  student_ln150_income?: number
  student_contribution?: number
  student_contrib_exempt: string
  spouse_contrib_exempt: string
  spouse_contribution?: number
  spouse_ln150_income?: number
  student_contribution_review: string
  spouse_contribution_review: string
  parent_contribution_review: string
  student_family_size?: number
  student_expected_contribution?: number
  student_previous_contribution?: number
  spouse_expected_contribution?: number
  spouse_previous_contribution?: number
  student_contribution_override?: number
  spouse_contribution_override?: number
  parentProvinceId?: number
}

entity Attendance {
  id: number
  description: string
  is_active: boolean
}

enum CsfaAmount {
  FULL_AMOUNT_LOANS_AND_GRANTS: Full amount loans and grants
  GRANTS_AND_LOANS_UP_TO: Grants and loans up to
  GRANTS_ONLY: Grants only
}

entity Disability {
  id: number
  application_id: number
  disability_type_id: number
  description?: string
  verified_disability_need: boolean
}

entity Disbursement {
  id: number
  disbursement_type_id?: number
  assessment_id?: number
  funding_request_id: number
  disbursed_amount?: number
  due_date?: Date
  tax_year?: number
  issue_date?: Date
  paid_amount?: number
  change_reason_id?: number
  financial_batch_id?: number
  financial_batch_id_year?: number
  financial_batch_run_date?: Date
  financial_batch_serial_no?: number
  transaction_number?: string
  csl_cert_seq_number?: number
  ecert_sent_date?: Date
  ecert_response_date?: Date
  ecert_status?: string
  ecert_portal_status_id?: number
}


entity Institution {
  id: number
  name: string
  is_active: boolean
  federal_institution_code?: string
  institution_level_id: number
}

entity FundingRequest {
  id: number
  application_id: number
  request_type_id?: number
  status_id?: number
  status_reason_id?: number
  comments?: string
  custom_status?: string
  received_date?: Date
  status_date?: Date
  yea_request_amount?: number
  yea_request_type?: number
  csl_request_amount?: number
  is_csl_full_amount?: boolean
  is_csg_only: boolean
  entering_first_year?: boolean
  student_meet_hs_o_equiv_req?: boolean
  student_meet_residency_req?: boolean
  student_isnt_elig_f_fund_in_another_jur?: boolean
  student_is_in_ft_study?: boolean
  student_is_att_in_elig_prog_des_ps_inst?: boolean
  student_is_elig_for_airfare_trvl_amount?: boolean
  student_is_mov_to_anth_cmm_to_attd_prgm?: boolean
  student_is_maintening_two_residences?: boolean
  student_w_not_receive_fund_from_otr_org?: boolean
}

enum FundingSource {
  CANADA_STUDENT_FINANCIAL_ASSISTANCE_FULL_TIME: Canada Student Financial Assistance (Full-Time)
}

entity Language {
  id: number
  description: string
  is_active: boolean
}

entity Person {
  id: number
  language_id?: number
  sex_id?: number
  birth_city_id?: number
  birth_province_id?: number
  birth_country_id?: number
  first_name?: string
  last_name?: string
  initials?: string
  previous_last_name?: string
  sin?: string
  citizenship_code?: number
  birth_date?: Date
  telephone?: string
  email?: string
}

entity PersonAddress {
  id: number
  person_id: number
  address_type_id: number
  address1?: string
  address2?: string
  city_id?: number
  province_id?: number
  country_id?: number
  postal_code?: string
  notes?: string
  telephone?: string
  email?: string
  is_active: boolean
}

entity Program {
  id: number
  description: string
  education_level_id: number
  is_active: boolean
}

entity Residence {
  id: number
  student_id: number
  address?: string
  city_id?: number
  province_id?: number
  country_id?: number
  postal_code?: string
  in_school?: number
  from_year?: number
  from_month?: number
  to_year?: number
  to_month?: number
  is_in_progress: boolean
}

entity RequestType {
  id: number
  application_type_id?: number
  funding_group_id?: number
  batch_group_id?: number
  description?: string
  scholarship_flag: number
  application_deadline?: string
  regulation?: string
  program_type?: string
  static_description_flag?: number
  financial_coding?: string
  t4a_required: boolean
  csg_other_flag?: number
  gl_budget?: number
  auto_appear?: string
  show_online: boolean
  short_name?: string
  help_url?: string
  help_text?: string
  is_active: boolean
}

entity Sex {
  id: number
  description: string
  is_active: boolean
}

entity Student {
  id: number
  person_id: number
  high_school_id?: number
  education_level_id?: number
  indigenous_learner_id?: number
  vendor_id?: string
  yukon_id?: string
  checked_for_yukon_id: boolean
  national_id?: string
  locator_number?: string
  is_crown_ward: boolean
  high_school_final_grade?: string
  high_school_left_year?: number
  high_school_left_month?: number
  pre_funded_year?: number
  pre_funding_years_used?: number
  csl_letter_date?: Date
  csl_warn_code?: string
  pre_over_award_amount?: number
  pre_yea_awards_used_amount?: number
  user_name?: string
  user_password?: string
  is_active: boolean
  is_first_logon_flg?: string
  last_logon_date?: Date
  last_pw_change_date?: Date
  yea_expiry_date?: Date
  adj_yg_funding_weeks?: number
  adj_sta_upgrading_weeks?: number
  adj_outside_travel_cnt?: number
  yukon_resident_from_month?: number
  yukon_resident_from_year?: number
  canadian_resident_from_month?: number
  canadian_resident_from_year?: number
  old_ytid?: string
  residence_comment?: string
  kin_first_name?: string
  kin_last_name?: string
  kin_address1?: string
  kin_address2?: string
  kin_city_id?: number
  kin_province_id?: number
  kin_country_id?: number
  kin_postal_code?: string
}

entity StudentConsent {
  id: number
  student_id: number
  start_academic_year_id: number
  end_academic_year_id?: number
  consent_person: string
  consent_sfa: boolean
  consent_csl: boolean
}

Application::attendance_id |o--o{ Attendance::id
Application::id }o--|{ FundingRequest::application_id
Application::institution_campus_id |o--o{ Institution::id
Application::primary_address_id |o--|| PersonAddress::id
Application::program_id |o--o{ Program::id
Assessment::funding_request_id |o--o{ FundingRequest::id
CsfaAmount ||--|| FundingSource::CANADA_STUDENT_FINANCIAL_ASSISTANCE_FULL_TIME
Disability::application_id ||--o{ Application::id
Disbursement::assessment_id |o--o{ Assessment::id
FundingRequest::request_type_id |o--o{ RequestType::id
Person::id }o--|| PersonAddress::person_id
Person::language_id |o--o{ Language::id
Person::sex_id |o--o{ Sex::id
PersonAddress::address_type_id ||--o{ AddressType::id
Residence::student_id ||--o{ Student::id
RequestType::description ||--|| FundingSource
Student::id }o--|| Application::student_id
Student::person_id ||--o| Person::id
StudentConsent::student_id ||--o{ Student::id
@enduml
