-- DROPS
DROP TABLE IF EXISTS sfa.file_reference
DROP TABLE IF EXISTS sfa.student_auth
DROP TABLE IF EXISTS sfa.application_draft

DROP TABLE IF EXISTS sfa.entitlement_error
DROP TABLE IF EXISTS sfa.disbursement
DROP TABLE IF EXISTS sfa.csl_nars_history
DROP TABLE IF EXISTS sfa.assessment
DROP TABLE IF EXISTS sfa.communication_log
DROP TABLE IF EXISTS sfa.requirement_met
DROP TABLE IF EXISTS sfa.correspondence_request_status
DROP TABLE IF EXISTS sfa.parent_resident
DROP TABLE IF EXISTS sfa.parent_dependent
DROP TABLE IF EXISTS sfa.msfaa_email_log
DROP TABLE IF EXISTS sfa.msfaa
DROP TABLE IF EXISTS sfa.investment
DROP TABLE IF EXISTS sfa.application_part_time_reason
DROP TABLE IF EXISTS sfa.funding_request
DROP TABLE IF EXISTS sfa.expense
DROP TABLE IF EXISTS sfa.disability_requirement
DROP TABLE IF EXISTS sfa.disability
DROP TABLE IF EXISTS sfa.dependent_eligibility
DROP TABLE IF EXISTS sfa.course_enrolled
DROP TABLE IF EXISTS sfa.agency_assistance
DROP TABLE IF EXISTS sfa.application
DROP TABLE IF EXISTS sfa.communication
DROP TABLE IF EXISTS sfa.correspondence_type_batch_param
DROP TABLE IF EXISTS sfa.correspondence_batch_param
DROP TABLE IF EXISTS sfa.correspondence
DROP TABLE IF EXISTS sfa.correspondence_type
DROP TABLE IF EXISTS sfa.dependent
DROP TABLE IF EXISTS sfa.education
DROP TABLE IF EXISTS sfa.expense_category
DROP TABLE IF EXISTS sfa.institution_request_type
DROP TABLE IF EXISTS sfa.request_requirement
DROP TABLE IF EXISTS sfa.request_type
DROP TABLE IF EXISTS sfa.residence
DROP TABLE IF EXISTS sfa.student_consent
DROP TABLE IF EXISTS sfa.yg_cost
DROP TABLE IF EXISTS sfa.yea_update
DROP TABLE IF EXISTS sfa.yea
DROP TABLE IF EXISTS sfa.verification_log
DROP TABLE IF EXISTS sfa.transportation
DROP TABLE IF EXISTS sfa.system_parameter
DROP TABLE IF EXISTS sfa.system_dep_params
DROP TABLE IF EXISTS sfa.study_tax_rate
DROP TABLE IF EXISTS sfa.study_area
DROP TABLE IF EXISTS sfa.study_field
DROP TABLE IF EXISTS sfa.student_living_allowance
DROP TABLE IF EXISTS sfa.student_contribution
DROP TABLE IF EXISTS sfa.student_category
DROP TABLE IF EXISTS sfa.status_reason
DROP TABLE IF EXISTS sfa.status
DROP TABLE IF EXISTS sfa.standard_of_living
DROP TABLE IF EXISTS sfa.sta_lookup
DROP TABLE IF EXISTS sfa.spouse_tax_rate
DROP TABLE IF EXISTS sfa.sfa_document_link
DROP TABLE IF EXISTS sfa.requirement_type
DROP TABLE IF EXISTS sfa.report_expense_category
DROP TABLE IF EXISTS sfa.prestudy_tax_rate
DROP TABLE IF EXISTS sfa.prestudy_employment_status
DROP TABLE IF EXISTS sfa.portal_status
DROP TABLE IF EXISTS sfa.period
DROP TABLE IF EXISTS sfa.part_time_reason
DROP TABLE IF EXISTS sfa.parent_contribution_formula
DROP TABLE IF EXISTS sfa.ownership
DROP TABLE IF EXISTS sfa.marital_status
DROP TABLE IF EXISTS sfa.investment_type
DROP TABLE IF EXISTS sfa.instruction_type
DROP TABLE IF EXISTS sfa.info_category
DROP TABLE IF EXISTS sfa.funding_group
DROP TABLE IF EXISTS sfa.first_nation
DROP TABLE IF EXISTS sfa.entitlement_error_codes
DROP TABLE IF EXISTS sfa.disbursement_type
DROP TABLE IF EXISTS sfa.disability_type
DROP TABLE IF EXISTS sfa.disability_service
DROP TABLE IF EXISTS sfa.csl_restricted
DROP TABLE IF EXISTS sfa.csl_reason
DROP TABLE IF EXISTS sfa.csl_nslsc_address
DROP TABLE IF EXISTS sfa.csl_lookup
DROP TABLE IF EXISTS sfa.csl_code
DROP TABLE IF EXISTS sfa.csg_threshold
DROP TABLE IF EXISTS sfa.csg_lookup
DROP TABLE IF EXISTS sfa.communication_type
DROP TABLE IF EXISTS sfa.child_care_ceiling
DROP TABLE IF EXISTS sfa.change_reason
DROP TABLE IF EXISTS sfa.category
DROP TABLE IF EXISTS sfa.batch_parameter
DROP TABLE IF EXISTS sfa.batch_group
DROP TABLE IF EXISTS sfa.assessment_type
DROP TABLE IF EXISTS sfa.application_type
DROP TABLE IF EXISTS sfa.agency
DROP TABLE IF EXISTS sfa.age_distribution
DROP TABLE IF EXISTS sfa.aboriginal_status
DROP TABLE IF EXISTS sfa.student_persons
DROP TABLE IF EXISTS sfa.student
DROP TABLE IF EXISTS sfa.high_school
DROP TABLE IF EXISTS sfa.person_address
DROP TABLE IF EXISTS sfa.person
DROP TABLE IF EXISTS sfa.address_type
DROP TABLE IF EXISTS sfa.sex
DROP TABLE IF EXISTS sfa.relationship
DROP TABLE IF EXISTS sfa.program
DROP TABLE IF EXISTS sfa.field_program
DROP TABLE IF EXISTS sfa.language
DROP TABLE IF EXISTS sfa.education_level
DROP TABLE IF EXISTS sfa.institution_campus_dates
DROP TABLE IF EXISTS sfa.institution_campus_notes
DROP TABLE IF EXISTS sfa.institution_campus
DROP TABLE IF EXISTS sfa.institution
DROP TABLE IF EXISTS sfa.institution_level
DROP TABLE IF EXISTS sfa.city
DROP TABLE IF EXISTS sfa.province
DROP TABLE IF EXISTS sfa.country
DROP TABLE IF EXISTS sfa.indigenous_learner
DROP TABLE IF EXISTS sfa.academic_year
DROP TABLE IF EXISTS sfa.citizenship
DROP TABLE IF EXISTS sfa.csl_classification
DROP TABLE IF EXISTS sfa.attendance
DROP TABLE IF EXISTS sfa.program_division
DROP TABLE IF EXISTS sfa.document_status
DROP TABLE IF EXISTS sfa.income
DROP TABLE IF EXISTS sfa.income_type
DROP TABLE IF EXISTS sfa.equipment_category
DROP TABLE IF EXISTS sfa.equipment_required
DROP TABLE IF EXISTS sfa.vendor_update
--DROP TABLE sfa.user
DROP TABLE IF EXISTS sfa.file_reference
