export default {
    students: [
        {title:"Address Type", path: "/administration/address-type"},
        {title:"Indigenous Learner", path: "/administration/indigenous-learner"},
        {title:"Language", path: "/administration/language"},
        {title:"Marital Status", path: "/administration/marital-status"},
        {title:"Parental Relationship", path: "/administration/parental-relationship"},
        {title:"First Nation", path: "/administration/first-nation"},
        {title:"High School", path: "/administration/high-school"},
        {title:"Portal Status", path: "/administration/portal-status"},
        {title:"Sex", path: "/administration/sex"},
        {title:"Student Category", path: "/administration/student-category"},
        {title:"Age Distribution", path: "/administration/age-distribution"},
        {title:"Education Level", path: "/administration/education-level"},
        {title:"Yukon Grant Eligibility", path: "/administration/yukon-grant-eligibility"},
        {title:"Aboriginal Status", path: "/administration/aboriginal-status"},
    ],
    location: [
        {title:"Province", path: "/administration/province"},
        {title:"Cities", path: "/administration/cities"},
        {title:"Countries", path: "/administration/countries"},
    ],
    
    institutions: [
        {title:"Institutions", path: "/administration/institutions"},
        {title:"CSL NSLSC Address Table", path: "/administration/csl-nslsc-address-table"},
        {title:"Institution Search", path: "/administration/institution-search"},
        {title:"Institution Level", path: "/administration/institution-level"},
    ],
    application: [
        {title:"Study Field", path: "/administration/study-field"},
        {title:"Application Type", path: "/administration/application-type"},
        {title:"Disbursement Type", path: "/administration/disbursement-type"},
        {title:"Disability Type with CSL Code", path: "/administration/disability-type"},
        {title:"Disability Type without CSL Code", path: "/administration/disability-type-without-csl"},
        {title:"Disability Services Required", path: "/administration/disability-service"},
    ],
    assessment: [
        {title:"Assessment Type", path: "/administration/assessment-type"},
        {title:"Batch group", path: "/administration/batch-group"},
        {title:"Reasons for Change", path: "/administration/reasons-for-change"},
        {title:"Funding Group", path: "/administration/funding-group"},
        {title:"Status", path: "/administration/status"},
        {title:"Status Reason", path: "/administration/status-reason"},
    ],
};